/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    // DEV-only panels are absent from production JS and must not add utilities to its CSS.
    ...(process.env.NODE_ENV === 'production' ? ['!./src/components/devtools/**'] : []),
  ],
  theme: {
    extend: {
      colors: {
        gm: {
          canvas: 'var(--gm-canvas)',
          surface: 'var(--gm-surface)',
          'surface-elevated': 'var(--gm-surface-elevated)',
          'surface-overlay': 'var(--gm-surface-overlay)',
          'surface-hover': 'var(--gm-surface-hover)',
          border: 'var(--gm-border)',
          'border-subtle': 'var(--gm-border-subtle)',
          'border-focus': 'var(--gm-border-focus)',
          'border-hover': 'var(--gm-border-hover)',
          primary: 'var(--gm-primary)',
          'primary-hover': 'var(--gm-primary-hover)',
          'primary-active': 'var(--gm-primary-active)',
          'primary-subtle': 'var(--gm-primary-subtle)',
          accent: 'var(--gm-accent)',
          'accent-subtle': 'var(--gm-accent-subtle)',
          text: 'var(--gm-text)',
          'text-secondary': 'var(--gm-text-secondary)',
          'text-tertiary': 'var(--gm-text-tertiary)',
          'text-disabled': 'var(--gm-text-disabled)',
          'text-on-primary': 'var(--gm-text-on-primary)',
          success: 'var(--gm-success)',
          warning: 'var(--gm-warning)',
          error: 'var(--gm-error)',
        },
      },
      fontFamily: {
        sans: ['Nunito', 'Noto Sans SC', 'Zen Maru Gothic', 'system-ui', 'sans-serif'],
        display: ['Nunito', 'Zen Maru Gothic', 'sans-serif'],
        mono: ['JetBrains Mono', 'Cascadia Code', 'monospace'],
      },
      fontSize: {
        display: ['24px', { lineHeight: '1.3', letterSpacing: '-0.3px', fontWeight: '700' }],
        title: ['18px', { lineHeight: '1.4', letterSpacing: '-0.2px', fontWeight: '700' }],
        body: ['14px', { lineHeight: '1.5715' }],
        caption: ['12px', { lineHeight: '1.4' }],
        micro: ['11px', { lineHeight: '1.3' }],
      },
      spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
        '3xl': '48px',
      },
      borderRadius: {
        DEFAULT: '18px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '18px',
        xl: '24px',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 2px 4px 0 rgba(61, 52, 40, 0.06)',
        DEFAULT: '0 3px 10px 0 rgba(61, 52, 40, 0.1)',
        md: '0 3px 10px 0 rgba(61, 52, 40, 0.1)',
        lg: '0 8px 24px 0 rgba(61, 52, 40, 0.14)',
      },
      transitionDuration: {
        fast: '150ms',
        DEFAULT: '250ms',
        slow: '350ms',
      },
      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
}
